complete -c termux-media-player -f -d "Termux Media Player"
complete -c termux-media-player -a help -d "Get help for termux-media-player"
complete -c termux-media-player -a info -d "Display current playback information"
complete -c termux-media-player -a play -d "Resume/Play specific media file"
complete -c termux-media-player -a pause -d "Pauses playback"
complete -c termux-media-player -a stop -d "Quits playback"
