complete -c termux-download -f -d "Download a resource using system download manager"
complete -c termux-download -s h -d "Get help for termux-download"
complete -c termux-download -s t -d "Title for download request notification"
complete -c termux-download -s d -d "Description for download request notification"
complete -c termux-download -s p -d "Full path to which the file should be downloaded"
